import React, { useEffect, useState} from 'react';
import { StyleSheet, View, Text, TouchableOpacity, Animated } from 'react-native';
// import components
import AreaDropdown, { DropdownItem } from '@/components/areaDropdown'; 
import NodalGraph from '@/components/NodalGraph';
import { AddAreaButton } from '@/components/addArea';
import { AddLandmarkButton } from '@/components/addLandmark';
import { AddTrashbinButton } from '@/components/AddTrashbin';
import { RemoveButton } from '@/components/RemoveButton';
import { AddDetailsModal, PopupType } from '@/components/AddDetailsModal';

//import api functions
import { AreaInput, LandmarkInput, WastebinInput } from '@/api/wastebins/wb_queries';
import { fetchAllAreas, fetchMapDataByArea, createArea, updateArea, deleteArea, } from '@/api/wastebins/wb_queries';
import { createLandmark, updateLandmark, deleteLandmark } from '@/api/wastebins/wb_queries';
import { createWastebin, fetchWastebinDetails, updateWastebin, deleteWastebin } from '@/api/wastebins/wb_queries';
import { insertNetworkEdges, WEIGHT_MAP, UIWeight } from '@/api/edges/edges_queries';

import { s } from 'react-native-size-matters';

import { MOCK_DATABASE_BY_AREA, SupabaseLandmarkPayload } from '@/constants/mockData';


export default function IndexScreen() {
  const [areaData, setAreaData] = useState<DropdownItem[]>([]);
  const [selectedAreaId, setSelectedAreaId] = useState<string | null>("area-1");
  const [mapData, setMapData] = useState<SupabaseLandmarkPayload[]>([]);
  //for zooming
  const [scaleValue] = useState(new Animated.Value(1));

  const handleZoom = (type: 'IN' | 'OUT') => {
    let currentScale = (scaleValue as any)._value;
    let nextScale = type === 'IN' ? currentScale + 0.2 : currentScale - 0.2;

    // Boundary limits: Don't let it shrink past 40% or grow past 200%
    if (nextScale < 0.4) nextScale = 0.4;
    if (nextScale > 2.0) nextScale = 2.0;

      Animated.timing(scaleValue, {
      toValue: nextScale,
      duration: 150,
      useNativeDriver: true,
    }).start();
  };
  //until here zooming

  // for popup modal editing
  const [modalVisible, setModalVisible] = useState(false);
  const [activePopupType, setActivePopupType] = useState<PopupType>(null);

  const existingNodesList = mapData.flatMap((landmark) => {
  // 1. Add the landmark itself to the choices
  const nodes = [{ id: landmark.landmark_id, name: landmark.landmark_name, type: 'landmark' as const }];
  
  // 2. Add its connected wastebins to the choices
  const bins = (landmark.wastebins || []).map(bin => ({
    id: bin.wastebin_id, // Assuming your database wastebin row has an 'id'
    name: `🗑️ ${bin.description || 'Trashbin'}`,
    type: 'wastebin' as const
  }));

  return [...nodes, ...bins];
});

  // State tracking context info generated by UI interactions
  const [activeContext, setActiveContext] = useState<{
    x_position?: number;
    y_position?: number;
    area_id?: string;
    landmark_id?: string;
  }>({});

  // Mock workspace tap handler
  const triggerAddNodeOnCanvas = (type: PopupType, clickX: number, clickY: number) => {
    setActiveContext({
      x_position: clickX,
      y_position: clickY,
      area_id: 'current-active-campus-area-uuid', // Dynamic ID context tracking
      landmark_id: 'current-active-landmark-uuid',
    });
    setActivePopupType(type);
    setModalVisible(true);
  };

  // Handles any valid structured payload outputted by the Modal layer
  // 1. Update the parameter signature to accept the bundle layout
const handleSavePayload = async (bundle: {
  type: 'AREA' | 'LANDMARK' | 'TRASHBIN';
  nodeData: AreaInput | LandmarkInput | WastebinInput;
  edgeData: {
    target_node_id: string;
    target_type: 'landmark' | 'wastebin';
    chosenUIWeight: UIWeight;
  } | null;
}) => {

  try {
    // ==========================================
    // PHASE 1: EXECUTE AREA CREATION CRUD
    // ==========================================
    if (bundle.type === 'AREA') {
      console.log("Inserting new area into Supabase:", bundle.nodeData);
      
      const areaInput = bundle.nodeData as AreaInput; // Explicitly cast the type

      const result = await createArea({
        area_name: areaInput.area_name // Now TypeScript knows this is 100% safe!
      });

      if (result.success) {
        console.log("Area created successfully in database!", result.data);
        
        // 2. Refresh the dropdown menu items list instantly
        const updatedAreas = await loadAreas();
        
        // 3. Auto-select the newly created area so the admin can start adding nodes to it immediately
        if (result.data?.id) {
          setSelectedAreaId(String(result.data.id));
        } else if (updatedAreas.length > 0) {
          // Fallback to the last item in the list if ID extraction fails
          setSelectedAreaId(String(updatedAreas[updatedAreas.length - 1].value));
        }
        
      } else {
        alert("Failed to create area: " + result.error?.message);
      }
      
      setModalVisible(false);
      return; // Stop here since Areas don't need network routing edge logic!
    }

    // ==========================================
    // PHASE 2 & 3: (Landmarks & Trashbins logic will live down here later)
    // ==========================================

  } catch (error) {
    console.error("Error running the area save routine layout orchestration:", error);
  }

};

  // Helper to open the pop-up with the right configuration
  const openPopup = (type: PopupType) => {
    setActivePopupType(type);
    setModalVisible(true);
  };

 

  //for mock data
      const loadAreas = async (): Promise<DropdownItem[]> => {
      try {
        const data = await fetchAllAreas(); // Runs your real Supabase call
        
        // Create ONLY your real database area item arrays first
    const dbAreas: DropdownItem[] = (data || []).map((area: any) => ({
      label: area.area_name,
      value: String(area.area_id), 
    }));

    // Attach system control layout items for rendering display 
    setAreaData([
      ...dbAreas,
      { label: '+ Add New Area', value: 'add_new' },
      { label: '❌ Delete Current Area', value: 'delete_current' }
    ]);

    return dbAreas; // Return ONLY the valid DB elements array block!

      } catch (error) {
        console.error("Error loading areas into dropdown layout:", error);
        return[];
      }
    };

    useEffect(() => {
  loadAreas();
}, []);
  // 2. Define your list data exactly matching your mockup

  // 3. Handle what happens when a user clicks an area
  const handleAreaSelect = async (item: DropdownItem) => {
    if (item.value === 'add_new') {
      openPopup('AREA');
      console.log('Open modal or prompt to add a new area!');
    } else if(item.value === 'delete_current') {
    if (!selectedAreaId) return;

      // Quick confirmation alert layout warning
    const confirmDelete = confirm("WARNING: Deleting this Area will permanently wipe out all its nested Landmarks, Wastebins, and Routing Edges. Do you want to continue?");
    
    if (confirmDelete) {
      const result = await deleteArea(selectedAreaId);
      if (result.success) {
        console.log("Area and all cascaded children removed from database.");
       // 2. Fetch fresh database data down right away to see what remains
        const remainingAreas = await loadAreas();
        
        // 3. Dynamic Fallback: Auto-route user view to the first remaining area slot if possible
        if (remainingAreas.length > 0) {
          setSelectedAreaId(String(remainingAreas[0].value));
        } else {
          setSelectedAreaId(null); // Completely clear the canvas view if zero records remain
        }
      } else {
        alert("Could not complete the request: " + result.error?.message);
      }
    }
  }

  else {
    setSelectedAreaId(String(item.value));
  }
};

  

  const handleLandmarkPress = () => console.log('Landmark clicked!');
  const handleTrashbinPress = () => console.log('Trashbin clicked!');
  const handleAreaPress = () => console.log('Area clicked!');
  const handleRemovePress = () => console.log('Remove clicked!');


  return (
    <View style={styles.container}>

        <View style = {styles.dropdownContainer}>
          {/* Dropdown Component nested*/}
                  <AreaDropdown 
                  data={areaData} 
                  placeholder="CHOOSE AREA" 
                  onSelect={handleAreaSelect}
                  selectedValue={selectedAreaId}
                  />
        </View>

        <View style = {styles.graphWindow}>
          <Text style={{ color: 'white' }}>Node and Graph Area (The Blue Square)</Text>
                  {/* PASS THE DATA STATE DOWN TO THE GRAPH COMPONENT */}
                              <Animated.View style={[ //For zooming 
                              styles.canvas, 
                              { transform: [{ scale: scaleValue }] }
                            ]}>
                              <NodalGraph mapData={mapData} />
                              </Animated.View>


                            //Zooming
                              <View style={styles.zoomControls}>
                                  <TouchableOpacity style={styles.zoomBtn} onPress={() => handleZoom('IN')}>
                                    <Text style={styles.zoomText}>+</Text>
                                  </TouchableOpacity>
                                  <TouchableOpacity style={styles.zoomBtn} onPress={() => handleZoom('OUT')}>
                                    <Text style={styles.zoomText}>−</Text>
                                  </TouchableOpacity>
                           </View>
                </View>
        
        
        <View style = {styles.buttonContainer}>
          <RemoveButton onPress = {handleRemovePress}/>
        <View style = {styles.buttonWrapper}>
          <AddLandmarkButton onPress = {() => openPopup('LANDMARK')}/>
          <AddTrashbinButton onPress = {() => openPopup('TRASHBIN')}/>
          <AddAreaButton onPress = {() => openPopup('AREA')}/>
        </View>
        </View>
      
      <AddDetailsModal 
      visible={modalVisible}
      type={activePopupType}
      contextData={activeContext}
      existingNodesList={existingNodesList} // <-- PASS THE NODE CHOICE LIST HERE
      onClose={() => setModalVisible(false)}
      onSave={handleSavePayload} // <-- RENAME OR POINT TO COMPREHENSIVE SAVING FLOW
    />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flexDirection: 'column',
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#EFFAFF', // Using the soft background color from your Figma image
    padding: 20,
  },
  dropdownContainer: {
    // CRITICAL: zIndex ensures the dropdown menu renders OVER the graph
    zIndex: 10, 
    marginBottom: 20, // Space between dropdown and graph
    justifyContent: 'center',
  },
  buttonWrapper: {
    paddingHorizontal: 20,
    marginTop: 10,             // Spacing directly under the blue graph window
    marginBottom: 10,          // Spacing between the button and the nav bar
  },
  placeholderDropdown: {
    height: 50,
    backgroundColor: '#fff',
    justifyContent: 'center',
    paddingHorizontal: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  graphWindow: {
    flex: 1, // Fills the rest of the available space
    backgroundColor: '#B6D7E8', // The "blue square"
    borderRadius: 0,
    borderColor: '#6D6D6D',
    borderWidth: 3,
    
    // CRITICAL: This is what creates the "window" effect. 
    // Anything drawn outside the bounds of this View is clipped.
    overflow: 'hidden', 
    
    // Optional: Centering content inside for now
    justifyContent: 'center', 
    alignItems: 'center',
    margin: s(5),
    marginHorizontal: 20,
  },
  canvas: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  zoomControls: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 8,
    padding: 4,
  },
  zoomBtn: {
    padding: 8,
    alignItems: 'center',
  },
  zoomText: { fontSize: 20, fontWeight: 'bold', color: '#1E56A0' },
  buttonContainer: {
    flex: 1,
    justifyContent: 'space-evenly',
    alignItems: 'center',
    flexWrap: 'nowrap',
    flexDirection: 'row',
    alignContent: 'center',
    paddingHorizontal: 20,
    marginTop: 10,             // Spacing directly under the blue graph window
    marginBottom: 10,
  }
});

 